CREATE DATABASE movies;

CREATE TABLE IF NOT EXIST my_movies(
    id BIGSIREAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100) NOT NULL,
    duration NUMERIC(2,1) NOT NULL,
    price NUMERIC(3,2) NOT NULL
);


